export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const QUESTION_LOADING = 'QUESTION_LOADING';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const GET_ERRORS_LOADING = 'GET_ERRORS_LOADING';

export const GET_MALADIE = 'GET_MALADIE';
export const ADD_MALADIE = 'ADD_MALADIE';
export const GET_ONE_MALADIE = 'GET_ONE_MALADIE';
export const DELETE_MALADIE = 'DELETE_MALADIE';
export const UPDATE_MALADIE = 'UPDATE_MALADIE';
export const MALADIE_LOADING = 'MALADIE_LOADING';
export const GET_ERRORS_MALADIE = 'GET_ERRORS_MALADIE';

export const GET_VACCIN = 'GET_VACCIN';
export const ADD_VACCIN = 'ADD_VACCIN';
export const GET_ONE_VACCIN = 'GET_ONE_VACCIN';
export const DELETE_VACCIN = 'DELETE_VACCIN';
export const UPDATE_VACCIN = 'UPDATE_VACCIN';
export const VACCIN_LOADING = 'VACCIN_LOADING';
export const GET_ERRORS_VACCIN = 'GET_ERRORS_VACCIN';

export const GET_SANTE = 'GET_SANTE';
export const ADD_SANTE = 'ADD_SANTE';
export const GET_ONE_SANTE = 'GET_ONE_SANTE';
export const DELETE_SANTE = 'DELETE_SANTE';
export const UPDATE_SANTE = 'UPDATE_SANTE';
export const SANTE_LOADING = 'SANTE_LOADING';
export const GET_ERRORS_SANTE = 'GET_ERRORS_SANTE';

export const GET_VOYAGE = 'GET_VOYAGE';
export const ADD_VOYAGE = 'ADD_VOYAGE';
export const GET_ONE_VOYAGE = 'GET_ONE_VOYAGE';
export const DELETE_VOYAGE = 'DELETE_VOYAGE';
export const UPDATE_VOYAGE = 'UPDATE_VOYAGE';
export const VOYAGE_LOADING = 'VOYAGE_LOADING';
export const GET_ERRORS_VOYAGE = 'GET_ERRORS_VOYAGE';

export const GET_MEDECIN = 'GET_MEDECIN';
export const ADD_MEDECIN = 'ADD_MEDECIN';
export const GET_ONE_MEDECIN = 'GET_ONE_MEDECIN';
export const DELETE_MEDECIN = 'DELETE_MEDECIN';
export const UPDATE_MEDECIN = 'UPDATE_MEDECIN';
export const MEDECIN_LOADING = 'MEDECIN_LOADING';
export const GET_ERRORS_MEDECIN = 'GET_ERRORS_MEDECIN';

export const GET_SEJOUR = 'GET_SEJOUR';
export const GET_SEJOURS = 'GET_SEJOURS';
export const ADD_SEJOUR = 'ADD_SEJOUR';
export const GET_ONE_SEJOUR = 'GET_ONE_SEJOUR';
export const DELETE_SEJOUR = 'DELETE_SEJOUR';
export const UPDATE_SEJOUR = 'UPDATE_SEJOUR';
export const SEJOUR_LOADING = 'SEJOUR_LOADING';
export const GET_ERRORS_SEJOUR = 'GET_ERRORS_SEJOUR';

export const GET_URGENCE = 'GET_URGENCE';
export const GET_URGENCES = 'GET_URGENCES';
export const ADD_URGENCE = 'ADD_URGENCE';
export const GET_ONE_URGENCE = 'GET_ONE_URGENCE';
export const DELETE_URGENCE = 'DELETE_URGENCE';
export const UPDATE_URGENCE = 'UPDATE_URGENCE';
export const URGENCE_LOADING = 'URGENCE_LOADING';
export const GET_ERRORS_URGENCE = 'GET_ERRORS_URGENCE';

export const GET_CENTRE = 'GET_CENTRE';
export const GET_CENTRES = 'GET_CENTRES';
export const ADD_CENTRE = 'ADD_CENTRE';
export const GET_ONE_CENTRE = 'GET_ONE_CENTRE';
export const DELETE_CENTRE = 'DELETE_CENTRE';
export const UPDATE_CENTRE = 'UPDATE_CENTRE';
export const CENTRE_LOADING = 'CENTRE_LOADING';
export const GET_ERRORS_CENTRE = 'GET_ERRORS_CENTRE';

export const GET_PAYS = 'GET_PAYS';
export const ADD_PAYS = 'ADD_PAYS';
export const GET_ONE_PAYS = 'GET_ONE_PAYS';
export const DELETE_PAYS = 'DELETE_PAYS';
export const UPDATE_PAYS = 'UPDATE_PAYS';
export const PAYS_LOADING = 'PAYS_LOADING';
export const GET_ERRORS_PAYS = 'GET_ERRORS_PAYS';
